### ISSUE TITLE
newest text keeps getting reloaded from ajax when deleted from admin

### ISSUE THREAD

**Issue by joshrowley** [joshrowley/captionator#1]
please fix

**Comment by joshrowley** [comment]
another comment

**Comment by kcurtin** [comment]
man, thats rough. did you clear your cache

**Comment by joshrowley** [comment]
nah, but i know what it is, i use the newest inserted div's timestamp to poll the server.

if i delete the newest div, the page thinks the next one is the latest one from the server, so it will then pull the newest one back down from the server since it's later than the top div.

basically need to put some logic that checks whether the sms message has been designated as deleted (i keep them in the db, in case the admin wants to restore)

**Comment by kcurtin** [comment]
this notification was a blast from the past. 👋 👋
